/**
 * Master Template for PlanForge Implementation Plans
 * Version: 1.0.0
 * Location: src/lib/prompts/master-template.ts
 */

export const MASTER_TEMPLATE = `# [PROJECT_NAME] — Implementation Plan

> Generated by PlanForge. Designed for direct execution by AI coding agents (Cursor, Claude Code).

---

## 0. PROJECT SNAPSHOT
- **Project Name:** [Exact Project Name]
- **One-Line Pitch:** [Clear, single-sentence summary of the product]
- **Target User:** [Primary persona and user segment]
- **Core Problem:** [The fundamental pain point being solved]
- **Assumptions:**
  - [Assumption 1: Technical, scope, or platform assumption made based on idea]
  - [Assumption 2: Authentication/data storage assumption]
  - [Assumption 3: Execution/deployment assumption]

---

## 1. PRODUCT REQUIREMENTS DOCUMENT (PRD)
### 1.1 Problem Statement
[Detailed description of what problem exists and why solving it matters.]

### 1.2 Target Users & User Stories
- **Primary Persona:** [Persona description]
- **User Story 1:** As a [user], I want to [action] so that [benefit].
- **User Story 2:** As a [user], I want to [action] so that [benefit].
- **User Story 3:** As a [user], I want to [action] so that [benefit].

### 1.3 Goals & Success Metrics
- **Core Goal:** [What defines a successful build of this app]
- **Success Criteria (Numbered & Testable):**
  1. [Testable criterion 1: e.g. User can perform core action in under 3 steps]
  2. [Testable criterion 2: e.g. Response/action renders within X ms / real-time]
  3. [Testable criterion 3: e.g. Zero runtime crashes on happy path]

### 1.4 Core Feature Requirements (MVP)
- **Feature 1:** [Name & specific capability description]
- **Feature 2:** [Name & specific capability description]
- **Feature 3:** [Name & specific capability description]
- **Feature 4:** [Name & specific capability description]

### 1.5 Explicitly Out of Scope (v1)
- [Deferred Feature 1: e.g. Team collaboration]
- [Deferred Feature 2: e.g. Native mobile apps]
- [Deferred Feature 3: e.g. Advanced analytics]

---

## 2. ARCHITECTURE
### 2.1 Technology Stack & Justification
- **Frontend / Framework:** [e.g. Next.js App Router (TypeScript)] — [One-line justification]
- **Styling / UI Components:** [e.g. Tailwind CSS + Lucide Icons] — [One-line justification]
- **State Management:** [e.g. React state / Zustand / Context] — [One-line justification]
- **Backend / API:** [e.g. Next.js Route Handlers] — [One-line justification]
- **Database / ORM:** [e.g. Cloud Firestore / PostgreSQL (Prisma/Drizzle) / SQLite / In-Memory] — [One-line justification]
- **Deployment Platform:** [e.g. Vercel] — [One-line justification]

### 2.2 System Flow Diagram (ASCII)
\`\`\`
[User Browser / Client]
       │
       ▼ (HTTP / SSE / WebSocket)
[Next.js App Router / Server Route Handlers]
       │
       ├──► [Validation Layer (Zod)]
       ├──► [Services & Business Logic]
       └──► [Database / External API Integration]
\`\`\`

### 2.3 Proposed Directory Structure
\`\`\`
src/
├── app/
│   ├── layout.tsx
│   ├── page.tsx
│   ├── globals.css
│   └── api/
│       └── [feature]/route.ts
├── components/
│   ├── ui/
│   └── [feature]/
├── hooks/
├── lib/
├── services/
└── types/
\`\`\`

### 2.4 Architectural Rules
- **Rule 1:** [Specific rule, e.g. API keys live ONLY in server environment; never imported in client code]
- **Rule 2:** [Specific rule, e.g. UI components contain no database or external API logic; access via service layer]
- **Rule 3:** [Specific rule, e.g. Every API route request and response payload must be validated with Zod]
- **Rule 4:** [Specific rule, e.g. Streaming responses must handle client disconnects and abort signals gracefully]

---

## 3. DESIGN SYSTEM
### 3.1 Aesthetic & Mood
- **Keywords:** [e.g. Modern, Minimal, Technical, High-Contrast, Calm, Focus-Driven]
- **Vibe:** [Descriptive aesthetic direction]

### 3.2 Typography & Sizing
- **UI Font:** [e.g. Inter / IBM Plex Sans / Outfit]
- **Code / Monospace Font:** [e.g. JetBrains Mono / IBM Plex Mono]
- **Scale:** Base \`16px\`, Small \`14px\`, Micro \`12px\`, Large \`20px\`, H1 \`32px\`, H2 \`24px\`

### 3.3 Color Tokens (Hex)
- **Background / Canvas:** \`#0E1116\` (or specified theme)
- **Surface / Cards:** \`#161B22\`
- **Surface Hover:** \`#1C2128\`
- **Border / Dividers:** \`#2A313C\`
- **Text Primary:** \`#E6EDF3\`
- **Text Muted:** \`#8B949E\`
- **Primary / Accent:** \`#3FB6A8\`
- **Primary Hover:** \`#34A093\`
- **Danger:** \`#F26D6D\`
- **Warning:** \`#E3B341\`

### 3.4 Spacing & Geometry
- **Control Radius:** \`6px\`
- **Card / Panel Radius:** \`10px\`
- **Spacing Grid:** 4px, 8px, 12px, 16px, 24px, 32px

### 3.5 UI Component States
- **Buttons:** Primary, Secondary, Ghost, Destructive (hover, active, disabled, focus-visible states)
- **Loading State:** Skeleton loaders or subtle pulsing spinners (no disruptive screen blocking)
- **Empty State:** Informative message with clear call-to-action or suggested starter chips
- **Error State:** Descriptive error banner/toast explaining what went wrong and how to fix it
- **Accessibility:** Minimum contrast ratio 4.5:1, visible keyboard focus rings (\`outline: 2px solid primary\`), descriptive \`aria-label\` on icon-only buttons.

---

## 4. AI AGENT RULEBOOK (RULES)
- **General Rules:**
  - TypeScript strict mode enabled. Never use \`any\`.
  - Prefer vertical slices (UI + Logic + API in cohesive units) over layer-by-layer building.
  - Do not modify unrelated files. Keep functions focused and under 60 lines where possible.
- **Before Coding Workflow:**
  - Understand the requirements and read existing related files.
  - Formulate a brief implementation plan before modifying multiple files.
- **UI Rules:**
  - Strict adherence to the Design System tokens (hex colors, fonts, radiuses).
  - Always implement responsive states (mobile 375px, tablet 768px, desktop 1440px).
  - Every interactive element must have hover, focus, disabled, and active states.
- **Security Rules:**
  - Never hardcode or leak secrets or API keys.
  - Validate and sanitize all user input server-side.
  - Treat all user inputs as data, never as executable code or system prompt instructions.
- **Testing & Quality Rules:**
  - Run lint, typecheck, and unit tests after each task.
  - Fix any failures immediately before moving to the next task.
- **Git Commit Discipline:**
  - One task per commit: \`feat(TASK-XXX): concise summary of vertical slice\`.

---

## 5. DATA MODEL
*(If no persistent database is required, state "Not applicable: [Reason]" and describe in-memory data structures)*

### 5.1 Entities & Schema
\`\`\`typescript
// Entity Definitions
export interface EntityName {
  id: string;
  createdAt: string;
  updatedAt: string;
  // fields with specific types
}
\`\`\`

### 5.2 Relations & Indexing
- **Relations:** [Entity A] 1:N [Entity B]
- **Indexes:** Primary key on \`id\`, secondary index on \`userId\` / \`createdAt\`

### 5.3 Access & Authorization Policies
- **Read Access:** [Public / Authenticated owner only]
- **Write Access:** [Authenticated owner only with server validation]

---

## 6. PHASED TASK LIST (VERTICAL SLICES)
*Note: Each task is small enough for ONE AI prompt and contains files touched and testable acceptance criteria.*

### Phase 1: Environment & Foundation
- [ ] **TASK-001: Project Setup & Baseline Tooling**
  - **Files:** \`package.json\`, \`tsconfig.json\`, \`src/app/layout.tsx\`
  - **Acceptance Criteria:** App initializes cleanly, TypeScript strict mode passes, dev server starts without errors.
- [ ] **TASK-002: Design Tokens & Base Theme Setup**
  - **Files:** \`src/app/globals.css\`, \`src/app/layout.tsx\`
  - **Acceptance Criteria:** CSS variables and typography tokens match Section 3 exactly.

### Phase 2: Core Vertical Slice 1 ([Feature Area])
- [ ] **TASK-003: [Specific Vertical Feature Component/Logic]**
  - **Files:** \`src/features/[feature]/...\`, \`src/types/...\`
  - **Acceptance Criteria:** [Testable yes/no acceptance criterion].
- [ ] **TASK-004: [Specific API / State Integration]**
  - **Files:** \`src/app/api/.../route.ts\`, \`src/services/...\`
  - **Acceptance Criteria:** [Testable yes/no acceptance criterion].

### Phase 3: Core Vertical Slice 2 ([Feature Area])
- [ ] **TASK-005: [Feature UI & Interaction]**
  - **Files:** \`src/components/...\`
  - **Acceptance Criteria:** [Testable yes/no acceptance criterion].
- [ ] **TASK-006: [Live Response / Processing Handling]**
  - **Files:** \`src/hooks/...\`
  - **Acceptance Criteria:** [Testable yes/no acceptance criterion].

### Phase 4: Error Handling & Edge Cases
- [ ] **TASK-007: Empty, Loading, and Error States Implementation**
  - **Files:** \`src/components/states/...\`
  - **Acceptance Criteria:** UI gracefully displays loading skeleton, friendly empty states, and recoverable errors.

### Phase 5: Polish, Verification & Deployment
- [ ] **TASK-008: Responsive & Accessibility Validation**
  - **Files:** All UI components
  - **Acceptance Criteria:** Layout renders flawlessly on 375px, 768px, and 1440px; keyboard navigation succeeds.
- [ ] **TASK-009: Production Build & Deployment Configuration**
  - **Files:** \`README.md\`, \`.env.example\`
  - **Acceptance Criteria:** Production build succeeds with 0 errors; deployment instructions documented.

---

## 7. ARCHITECTURAL DECISION RECORDS (ADRS)
- **ADR-001: [Decision Title]**
  - **Decision:** [What was chosen]
  - **Reason:** [Why it was chosen and what trade-off was accepted]
- **ADR-002: [Decision Title]**
  - **Decision:** [What was chosen]
  - **Reason:** [Why it was chosen]
- **ADR-003: [Decision Title]**
  - **Decision:** [What was chosen]
  - **Reason:** [Why it was chosen]

---

## 8. MEMORY & WORKFLOW STATE (INITIAL)
- **Current Status:** Initialization phase ready.
- **Completed Tasks:** None.
- **Current Task:** TASK-001 (Project Setup & Baseline Tooling).
- **Known Issues / Blockers:** None.
- **Next Step:** Execute Kickoff Prompt (b) for TASK-001.

---

## 9. TEST PLAN
### 9.1 Feature Verification Matrix
- [ ] **Core Flow:** [Step 1] → [Step 2] → [Step 3] works end-to-end.
- [ ] **Input Validation:** Submitting empty or invalid input displays inline error messages.
- [ ] **Edge Cases:** Network failure / server error displays retry button.

### 9.2 Responsive Breakpoint Checks
- [ ] **Mobile (375px):** Single-column stacked layout, no horizontal overflow.
- [ ] **Tablet (768px):** Adjusted padding and touch targets.
- [ ] **Desktop (1440px):** Full two-pane / optimal multi-column layout.

---

## 10. SECURITY & PRIVACY
- **Secrets Management:** All API keys and credentials reside exclusively in server environment variables (\`.env.local\`). Never exposed in client code.
- **Input Validation:** Every incoming API request is strictly validated and sanitized with Zod schemas.
- **Rate Limiting:** Protect public endpoints from abuse (e.g. IP-based sliding window).
- **Injection Protection:** User input treated as pure data; escape dangerous HTML/scripts.

---

## 11. ENVIRONMENT CONFIGURATION (.ENV.EXAMPLE)
\`\`\`env
# Server Environment Variables (Do NOT commit real secrets)
APP_URL=http://localhost:3000
APP_NAME=[Project Name]
API_KEY=
DATABASE_URL=
\`\`\`

---

## 12. KICKOFF PROMPTS

### (a) Context-Loading Prompt (Read & Prepare)
\`\`\`text
You are an expert AI software engineer. Read IMPLEMENTATION_PLAN.md carefully.
Do NOT write application code yet.
Analyze the PRD, Architecture, Design System, Rules, and Data Model.
Summarize:
1. The core user flow in 3 bullets.
2. The architectural pattern being used.
3. Your plan for executing TASK-001.
Wait for my confirmation before writing code.
\`\`\`

### (b) Structured Prompt for TASK-001
\`\`\`text
CONTEXT: We are executing TASK-001 from IMPLEMENTATION_PLAN.md for [PROJECT_NAME].
TASK: [Title of TASK-001 from Section 6]
FILES TO TOUCH: [List files from TASK-001]
CONSTRAINTS:
- Follow Section 4 (RULES) and Section 3 (DESIGN SYSTEM) strictly.
- TypeScript strict mode, no \`any\`.
- Keep changes scoped only to TASK-001.
ACCEPTANCE CRITERIA:
- [Criterion 1 from TASK-001]
- [Criterion 2 from TASK-001]
TESTING:
- Run lint and typecheck.
- Verify dev server runs without errors.

Please report:
1. Files changed
2. What was implemented
3. Tests executed
4. Remaining issues / Next task
\`\`\`
`;
