/**
 * Master Template for PlanForge Implementation Plans
 * Version: 2.0.0
 * Location: src/lib/prompts/master-template.ts
 */

export const MASTER_TEMPLATE = `# [PROJECT_NAME]: Implementation Plan

> Generated by PlanForge. Designed for direct execution by AI coding agents (Cursor, Claude Code).

---

## 0. PROJECT SNAPSHOT
- **Project Name:** [Exact Project Name]
- **One-Line Pitch:** [Clear, single-sentence summary of the product]
- **Scope Classification:** [tiny | standard | rich]
- **Locale & Domain Context:** [Detected currency e.g. ৳ (BDT) / $ (USD) / € (EUR), language, local service integrations, and number formatting]
- **Target User:** [Primary persona and user segment]
- **Core Problem:** [The fundamental pain point being solved]
- **Assumptions:**
  - [Assumption 1: Technical, scope, or platform assumption made based on idea]
  - [Assumption 2: Authentication/data storage assumption]
  - [Assumption 3: Execution/deployment assumption]

---

## 1. PRODUCT REQUIREMENTS DOCUMENT (PRD)
### 1.1 Problem Statement
[Detailed description of what problem exists and why solving it matters.]

### 1.2 Target Users & User Stories
- **Primary Persona:** [Persona description]
- **User Story 1:** As a [user], I want to [action] so that [benefit].
- **User Story 2:** As a [user], I want to [action] so that [benefit].
- **User Story 3:** As a [user], I want to [action] so that [benefit].

### 1.3 Goals, Success Metrics & Speed Targets
- **Core Goal:** [What defines a successful build of this app]
- **Speed & UX Targets:**
  - [Speed Target 1: e.g. Primary flow achievable in under 10 seconds, max 2 clicks/taps]
  - [Speed Target 2: e.g. Default inputs pre-populated with sensible defaults (today's date, previous category)]
- **Success Criteria (Numbered & Testable):**
  1. [Testable criterion 1: e.g. User can perform core action in under 3 steps]
  2. [Testable criterion 2: e.g. Response/action renders within X ms / real-time]
  3. [Testable criterion 3: e.g. Zero runtime crashes on happy path]

### 1.4 Core Feature Requirements (MVP Breakdown)
- **Module 1 ([Name]):** [Specific capabilities and requirements]
- **Module 2 ([Name]):** [Specific capabilities and requirements]
- **Module 3 ([Name]):** [Specific capabilities and requirements]
- **Module 4 ([Name]):** [Specific capabilities and requirements]

### 1.5 Explicitly Out of Scope (v1)
- [Deferred Feature 1: e.g. Team collaboration (Reason: single-user core focus for v1)]
- [Deferred Feature 2: e.g. Native mobile apps (Reason: responsive web first)]
- [Deferred Feature 3: e.g. Advanced AI analytics (Reason: establish reliable ledger first)]

---

## 2. ARCHITECTURE
### 2.1 Technology Stack & Justification
- **Frontend / Framework:** [e.g. Next.js App Router (TypeScript)]: [One-line justification]
- **Styling / UI Components:** [e.g. Tailwind CSS + Lucide Icons]: [One-line justification]
- **State Management:** [e.g. React state / Zustand / Server Actions]: [One-line justification]
- **Backend / API:** [e.g. Next.js Route Handlers / Server Actions]: [One-line justification]
- **Database / ORM:** [e.g. PostgreSQL (Supabase / Neon + Prisma/Drizzle)]: [One-line justification verified against host]
- **Authentication & Authorization:** [e.g. Supabase Auth / NextAuth with RLS]: [One-line justification]
- **Deployment Platform:** [e.g. Vercel / Railway]: [One-line justification]

### 2.2 System Flow Diagram (ASCII)
\`\`\`
[User Browser / Mobile Client]
       │
       ▼ (HTTPS / Server Actions / REST)
[Next.js App Router (Server-side Handlers)]
       │
       ├──► [Zod Validation Layer]
       ├──► [Business Logic & Service Layer]
       └──► [Database / Postgres (with RLS policies)]
\`\`\`

### 2.3 Proposed Directory Structure
\`\`\`
src/
├── app/
│   ├── layout.tsx
│   ├── page.tsx
│   ├── globals.css
│   └── api/
│       └── [feature]/route.ts
├── components/
│   ├── ui/
│   └── [feature]/
├── features/
│   └── [feature]/
│       ├── schema.ts
│       └── services.ts
├── hooks/
├── lib/
│   ├── db.ts
│   └── formatters.ts
└── types/
\`\`\`

### 2.4 Architectural Rules
- **Rule 1:** API keys and service-role secrets reside strictly in server environment; never imported in client code.
- **Rule 2:** UI components contain no database logic; data access is encapsulated in typed service layers.
- **Rule 3:** Every mutation and API route payload must be validated server-side with Zod.
- **Rule 4:** Money values stored strictly as integer minor units or Decimal; never floating-point numbers.

---

## 3. DESIGN SYSTEM (Anti-AI-Look)
### 3.1 Subject Anchor
- **Industry & Audience Vocabulary:** [2 lines explaining the product's real domain and audience from which the visual identity is derived]

### 3.2 Aesthetic Direction Evaluation
- **Candidate 1:** [Direction Name, Hue family, Font pairing, Mood]
- **Candidate 2:** [Direction Name, Hue family, Font pairing, Mood]
- **Candidate 3:** [Direction Name, Hue family, Font pairing, Mood]
- **Selected Direction:** [Chosen candidate]
- **Selection Rationale:** [One-line rationale tied to the product's domain, audience, and tactile feel]

### 3.3 Color Tokens (Light & Dark Mode)
- **Light Mode Palette:**
  - **Canvas / Background:** \`#HEX\` - [Role]
  - **Surface / Card:** \`#HEX\` - [Role]
  - **Border / Subtle:** \`#HEX\` - [Role]
  - **Text Primary:** \`#HEX\` - [Role]
  - **Text Secondary / Muted:** \`#HEX\` - [Role]
  - **Primary Accent:** \`#HEX\` - [Role]
- **Semantic Status Tokens (WCAG AA Contrast >= 4.5:1):**
  - **Success (e.g. Income/Active):** \`#HEX\` - [Muted, accessible green/emerald]
  - **Warning (e.g. Budget Alert):** \`#HEX\` - [Muted, accessible amber/orange]
  - **Danger (e.g. Expense/Overdue):** \`#HEX\` - [Muted, accessible ruby/crimson]
- **Dark Mode Palette:**
  - **Canvas (Dark):** \`#HEX\` - [Tinted dark neutral, never #000000 flat]
  - **Surface (Dark):** \`#HEX\` - [Card background]
  - **Border (Dark):** \`#HEX\` - [Subtle boundary]
  - **Text Primary (Dark):** \`#HEX\` - [High-legibility primary text]

### 3.4 Typography & Numbers / Data Rules
- **Primary Typography:** [Font Family, e.g. Plus Jakarta Sans / Satoshi / General Sans]
- **Secondary / Display:** [Font Family, e.g. Cabinet Grotesk / Newsreader / Archivo]
- **Numbers & Data Typography:**
  - Strict \`font-variant-numeric: tabular-nums\` for all tables, metric cards, and currency amounts.
  - Numbers right-aligned in tables; consistent decimal formatting.
  - Locale-aware digit formatting (e.g. \`1,00,000.00 ৳\` for BDT, \`$100,000.00\` for USD).

### 3.5 Layout Concept & ASCII Wireframes
- **Layout Philosophy:** [One-sentence prose layout philosophy with mobile-first thumb-reach rules]
- **ASCII Wireframe (Main Screen):**
\`\`\`
+-------------------------------------------------------------+
| [Header: App Name / Wallet Balance ৳ 45,250.00]             |
+-------------------------------------------------------------+
| Quick Actions: [+ Add Income]  [- Add Expense]  [Transfer]  |
+-------------------------------------------------------------+
| Recent Ledger:                                              |
| - Grocery (bKash) .......................... -৳ 1,250.00    |
| - Freelance Payment (Bank) ................. +৳ 35,000.00   |
| - Internet Bill (Nagad) .................... -৳ 1,000.00    |
+-------------------------------------------------------------+
| [Bottom Nav: Ledger | Budgets | Accounts | Reports]         |
+-------------------------------------------------------------+
\`\`\`

### 3.6 Spacing & Radius System
- **Spacing Scale:** [Deliberate scale: 4px, 8px, 12px, 16px, 24px, 32px]
- **Radius System:** Controls (6px), Cards/Panels (12px), Modals (16px)

### 3.7 Core Components, States & Microcopy
- **States:** Skeleton Loaders (shaped like real data rows), Empty States (with helpful human copy), Error States (actionable recovery).
- **Microcopy Guidance:** Real sentences in plain human voice matching the locale (e.g. "No transactions yet. Tap below to log your first expense.").

### 3.8 Signature Detail
- **Feature UI Moment:** [One specific, non-generic UI moment unique to this product, e.g. running-balance ledger line, monthly reconciliation summary, tactile quick-entry keyboard drawer].

### 3.9 Motion & Transitions
- [At most ONE orchestrated moment plus instant, tactile feedback on user actions].

### 3.10 Anti-Slop Blacklist
<!-- ANTI-SLOP-BLACKLIST-START -->
[Copy the full list provided in the ANTI-SLOP BLACKLIST block verbatim here]
<!-- ANTI-SLOP-BLACKLIST-END -->

---

## 4. AI AGENT RULEBOOK (RULES)
- **General Rules:**
  - TypeScript strict mode enabled. Never use \`any\`.
  - Build strictly in vertical slices (DB + Server Action + Zod + UI + Test) task-by-task.
  - Do not modify unrelated files. Keep functions focused and under 60 lines where possible.
- **Anti-Slop Rule:**
  - Follow the Anti-Slop Blacklist. Any violation is a defect.
- **Security Rules:**
  - Never leak server secrets or service-role keys to the client.
  - Validate all inputs server-side with Zod schemas.
  - Implement ownership verification on all update/delete mutations.
- **Testing & Quality Rules:**
  - Run lint, typecheck, and unit tests after each task.
  - Fix any failures immediately before proceeding to the next task.
- **Git Commit Discipline:**
  - One task per commit: \`feat(TASK-XXX): concise summary of vertical slice\`.

---

## 5. DATA MODEL
### 5.1 Relational Schema & Types
\`\`\`typescript
// Enums & Types
export type TransactionType = "INCOME" | "EXPENSE" | "TRANSFER";
export type AccountType = "CASH" | "BANK" | "MFS_BKASH" | "MFS_NAGAD";

// Entity Definitions
export interface Account {
  id: string;
  userId: string;
  name: string;
  type: AccountType;
  currency: string;
  createdAt: string;
  updatedAt: string;
}

export interface Transaction {
  id: string;
  userId: string;
  accountId: string;
  amountMinorUnits: number; // Stored in minor units (cents / poisha) e.g. 10000 = 100.00
  type: TransactionType;
  category: string;
  note: string | null;
  transactedAt: string;
  createdAt: string;
}
\`\`\`

### 5.2 Relations, Constraints & Indexes
- **Foreign Keys:** \`Transaction.accountId\` references \`Account.id\` ON DELETE RESTRICT
- **Constraints:** CHECK (\`amountMinorUnits > 0\`), NOT NULL on core attributes
- **Indexes:** Composite index on \`(userId, transactedAt DESC)\`, index on \`accountId\`

### 5.3 Concrete RLS / Authorization Policies
\`\`\`sql
-- Row Level Security (RLS) Policies
ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage own accounts" ON accounts
  FOR ALL USING (auth.uid() = user_id);

ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage own transactions" ON transactions
  FOR ALL USING (auth.uid() = user_id);
\`\`\`

### 5.4 Balance Calculation Strategy (ADR Reference)
- Documented in ADR-002: Dynamic ledger calculation with cached account snapshots to prevent balance drift.

---

## 6. PHASED TASK LIST (VERTICAL SLICES)
*Note: Each task is small enough for ONE AI prompt and contains explicit dependencies, observable acceptance criteria, and a strict Definition of Done.*

### Phase 1: Foundation & Baseline (Max 3 Tasks)
- [ ] **TASK-001: Project Setup & Baseline Tooling**
  - **Goal:** Initialize project environment with TypeScript strict mode, linter, and testing harness.
  - **Files:** \`package.json\`, \`tsconfig.json\`, \`src/app/layout.tsx\`
  - **Dependencies:** None
  - **Acceptance Criteria:** App initializes cleanly, TypeScript strict mode passes, dev server starts without errors.
  - **Definition of Done:** \`npm run build && npm test\` succeeds with 0 errors.

- [ ] **TASK-002: Design Tokens, CSS Variables & Theme Setup**
  - **Goal:** Configure CSS variables, dark mode tokens, typography, and tabular number utilities.
  - **Files:** \`src/app/globals.css\`, \`src/app/layout.tsx\`, \`tailwind.config.ts\`
  - **Dependencies:** TASK-001
  - **Acceptance Criteria:** CSS variables match Section 3 exactly; typography classes and color tokens available globally.
  - **Definition of Done:** \`npm run build\` succeeds; tokens verified in inspector.

- [ ] **TASK-003: Database Client & Migration Schema**
  - **Goal:** Set up database client, schema definitions, and RLS policies.
  - **Files:** \`src/lib/db.ts\`, \`src/types/schema.ts\`
  - **Dependencies:** TASK-001
  - **Acceptance Criteria:** Database connection helper instantiated; schema types match Section 5.
  - **Definition of Done:** Typecheck passes cleanly.

> 🛑 **STOP AND VERIFY (Phase 1):** Verify project builds, theme renders, and database client connects before beginning Phase 2.

### Phase 2: Core Vertical Slice 1 ([Primary Feature])
- [ ] **TASK-004: [Feature Name] Schema & Server Actions**
  - **Goal:** Implement data mutations with Zod validation and user ownership checks.
  - **Files:** \`src/features/[feature]/schema.ts\`, \`src/features/[feature]/actions.ts\`
  - **Dependencies:** TASK-002, TASK-003
  - **Acceptance Criteria:** User can submit valid mutation and record is saved in DB; invalid inputs return typed Zod errors.
  - **Definition of Done:** Unit test covering valid and invalid payload execution passes.

- [ ] **TASK-005: [Feature Name] UI & Form Interaction**
  - **Goal:** Build responsive UI component with tabular numerals and instant feedback.
  - **Files:** \`src/components/[feature]/...\`, \`src/app/[route]/page.tsx\`
  - **Dependencies:** TASK-004
  - **Acceptance Criteria:** User can interact with form, see loading skeleton during submit, and observe newly added item in list.
  - **Definition of Done:** Typecheck passes; component renders cleanly on mobile (375px) and desktop (1440px).

> 🛑 **STOP AND VERIFY (Phase 2):** Test primary creation and read flow end-to-end in browser. Confirm data persists accurately.

### Phase 3: Core Vertical Slice 2 ([Secondary Feature])
- [ ] **TASK-006: [Feature Name] Backend & Calculation Engine**
  - **Goal:** Implement secondary module business logic with drift-free calculations.
  - **Files:** \`src/features/[feature]/services.ts\`
  - **Dependencies:** TASK-004
  - **Acceptance Criteria:** Calculations compute accurately with testable sample data.
  - **Definition of Done:** Unit test verifying calculation edge cases passes.

- [ ] **TASK-007: [Feature Name] View & Interactive Controls**
  - **Goal:** Build interactive visualization or summary view.
  - **Files:** \`src/components/[feature]/...\`
  - **Dependencies:** TASK-006
  - **Acceptance Criteria:** View renders calculated data; empty state displays friendly human microcopy.
  - **Definition of Done:** Manual check confirms view updates reactively.

> 🛑 **STOP AND VERIFY (Phase 3):** Test cross-module interactions (e.g. transactions updating account balances).

### Phase 4: State Resilience, Legal & Completeness
- [ ] **TASK-008: Custom Skeleton Loaders & Core Error States**
  - **Goal:** Implement skeleton loaders matching real content dimensions and friendly error recovery views.
  - **Files:** \`src/components/states/...\`
  - **Dependencies:** TASK-005, TASK-007
  - **Acceptance Criteria:** Loading state displays custom animated skeletons (no bare spinners); network errors display retry buttons.
  - **Definition of Done:** Typecheck passes; verified across light and dark themes.

- [ ] **TASK-009: Terms of Service & Privacy Policy Pages**
  - **Goal:** Create real, localized legal pages and link them in the footer.
  - **Files:** \`src/app/terms/page.tsx\`, \`src/app/privacy/page.tsx\`, \`src/components/Footer.tsx\`
  - **Dependencies:** TASK-001
  - **Acceptance Criteria:** Real legal documents created and accessible via footer navigation links.
  - **Definition of Done:** Pages render with 0 broken links.

### Phase 5: Verification & Anti-Slop Polish
- [ ] **TASK-010: Anti-Slop Compliance Audit & Polish**
  - **Goal:** Audit entire UI against the Anti-Slop Blacklist.
  - **Files:** All UI components
  - **Dependencies:** All previous tasks
  - **Acceptance Criteria:** Finished UI rigorously evaluated against all Anti-Slop Blacklist rules with zero violations.
  - **Definition of Done:** Full manual visual pass confirms bespoke, hand-crafted appearance.

- [ ] **TASK-011: Production Build & Deployment Documentation**
  - **Goal:** Ensure production bundle succeeds with zero errors and update documentation.
  - **Files:** \`README.md\`, \`.env.example\`
  - **Dependencies:** TASK-010
  - **Acceptance Criteria:** Production build succeeds with 0 errors; deployment steps documented.
  - **Definition of Done:** \`npm run build\` exits 0.

---

## 7. ARCHITECTURAL DECISION RECORDS (ADRS)
- **ADR-001: [Stack & Host Architecture]**
  - **Decision:** [e.g. Next.js App Router + Supabase Postgres on Vercel]
  - **Reason:** [Matches serverless deployment constraints with managed relational database]
- **ADR-002: [Balance Calculation & Ledger Strategy]**
  - **Decision:** [e.g. Computed from immutable ledger transactions with periodic cached snapshots]
  - **Reason:** [Prevents balance drift and provides full financial auditability]
- **ADR-003: [Authentication & Access Control Model]**
  - **Decision:** [e.g. Row Level Security policies tied to authenticated user ID]
  - **Reason:** [Guarantees multi-tenant data isolation directly at the database layer]

---

## 8. MEMORY & WORKFLOW STATE (INITIAL)
- **Current Status:** Initialization phase ready.
- **Completed Tasks:** None.
- **Current Task:** TASK-001 (Project Setup & Baseline Tooling).
- **Known Issues / Blockers:** None.
- **Next Step:** Execute Kickoff Prompt (b) for TASK-001.

---

## 9. TEST PLAN
### 9.1 Feature Verification Matrix
- [ ] **Core Flow:** [Step 1] → [Step 2] → [Step 3] works end-to-end.
- [ ] **Input Validation:** Submitting empty or invalid input displays inline error messages.
- [ ] **Edge Cases:** Network failure / server error displays retry button.

### 9.2 Responsive Breakpoint Checks
- [ ] **Mobile (375px):** Single-column stacked layout, thumb-reachable controls, no horizontal overflow.
- [ ] **Tablet (768px):** Adjusted padding and touch targets.
- [ ] **Desktop (1440px):** Full multi-column / optimal data table layout.

---

## 10. SECURITY & PRIVACY
- **Secrets Management:** All API keys and credentials reside exclusively in server environment variables (\`.env.local\`). Never exposed in client code.
- **Input Validation:** Every incoming API request is strictly validated and sanitized with Zod schemas.
- **Ownership Verification:** Server actions verify \`auth.uid() === record.userId\` on every update/delete mutation.
- **CSV Formula Injection Sanitization:** Export routines escape dangerous leading characters (\`=\`, \`+\`, \`-\`, \`@\`).
- **Destructive Action Safety:** Confirmation dialogs required for irreversible actions (e.g. account deletion).
- **Rate Limiting:** Protect public endpoints from abuse.

---

## 11. ENVIRONMENT CONFIGURATION (.ENV.EXAMPLE)
\`\`\`env
# Server Environment Variables (Do NOT commit real secrets)
APP_URL=http://localhost:3000
APP_NAME=[Project Name]
DATABASE_URL=
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=
\`\`\`

---

## 12. KICKOFF PROMPTS

### (a) Context-Loading Prompt (Read & Prepare)
\`\`\`text
You are an expert AI software engineer. Read IMPLEMENTATION_PLAN.md carefully.
Do NOT write application code yet.
Analyze the PRD, Architecture, Design System, Rules, and Data Model.
Summarize:
1. The core user flow in 3 bullets.
2. The architectural pattern being used.
3. Your plan for executing TASK-001.
Wait for my confirmation before writing code.
\`\`\`

### (b) Structured Prompt for TASK-001
\`\`\`text
CONTEXT: We are executing TASK-001 from IMPLEMENTATION_PLAN.md for [PROJECT_NAME].
TASK: [Title of TASK-001 from Section 6]
FILES TO TOUCH: [List files from TASK-001]
CONSTRAINTS:
- Follow Section 4 (RULES) and Section 3 (DESIGN SYSTEM) strictly.
- TypeScript strict mode, no \`any\`.
- Keep changes scoped only to TASK-001.
ACCEPTANCE CRITERIA:
- [Criterion 1 from TASK-001]
- [Criterion 2 from TASK-001]
TESTING:
- Run lint and typecheck.
- Verify dev server runs without errors.

Please report:
1. Files changed
2. What was implemented
3. Tests executed
4. Remaining issues / Next task
\`\`\`
`;
